<?php


function mitd_nid($uid, $op_nid) {

	$query = new EntityFieldQuery();
	$query->entityCondition('entity_type', 'node')
	  ->entityCondition('bundle', 'proposals')
	  ->propertyCondition('status', 1) // published? yes
	  ->propertyCondition('uid', $uid)
	  ->fieldCondition('field_opportunity', 'nid', $op_nid);
	$result = $query->execute();

	if (isset($result['node'])) {
	  $items_nids = array_keys($result['node']);
	  $items = entity_load('node', $items_nids);
	}

	//print_r($result);
	return $result;

}

function mitd_opportunity_count($uid) {
	$query = db_select('node', 'n')
	  ->fields('n')
      ->condition('type', 'opportunity')
     ->condition('uid', $uid)
      ->countQuery()
      ->execute()
       ->fetchAssoc();
     return $query['expression'];
}

