<?php
/**
 * Implements hook_form_alter().
 */
function light_message_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'proposals_node_form') {
print_r($form_state);exit;
    $form['#submit'][] = 'light_message_proposals_node_form';
  }
}

/**
 * Additional handler for proposals_node form submit.
 */
function light_message_proposals_node_form($form, &$form_state) {
    
	$op_nid = $form_state['values']['field_opportunity']['und']['0']['nid'];
	$uid = $form_state['values']['uid'];
	$node = node_load($op_nid);		
    $message = message_create('notify_author_when_proposal_submit', array('uid' => $node->uid));
    $wrapper = entity_metadata_wrapper('message', $message);
    $wrapper->field_opportunity_ref->set($node);
    //$wrapper->field_opportunity_ref->set($node);
	$wrapper->save(); 
 }