<?php

/**
 * @file
 * Hides the comment subject if the "Allow comment title" checkbox is
 * unchecked for that node type.
 */

/**
 * Implements hook_preprocess_HOOK() for a comment.
 */
function comment_hide_subject_preprocess_comment(&$variables) {
  $node_type = $variables['node']->type;
  $subject_enabled = variable_get('comment_subject_field_' . $node_type, 0);
  
  if (!$subject_enabled) {
    // Don't display the comment title.
    $variables['title_attributes_array']['class'][] = 'element-invisible';
  }
}
